//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snappet.EFDesinger
{
    using System;
    using System.Collections.Generic;
    
    public partial class work
    {
        public int ID { get; set; }
        public Nullable<double> SubmittedAnswerId { get; set; }
        public Nullable<System.DateTime> SubmitDateTime { get; set; }
        public Nullable<bool> Correct { get; set; }
        public Nullable<double> Progress { get; set; }
        public Nullable<double> UserId { get; set; }
        public Nullable<double> ExerciseId { get; set; }
        public Nullable<double> Difficulty { get; set; }
        public string Subject { get; set; }
        public string Domain { get; set; }
        public string LearningObjective { get; set; }
    }
}
